### ISSUE TITLE
Node run failed with exit code 1 Error: child_process

### ISSUE THREAD

**Issue by mishmaccas** [DevExpress/testcafe-action#11]
Hello TestCafe Support
Sometimes when I am using testcafe-action to install TestCafe from npm and run the tests, the actions results in a false fail. The step fails.

Even though the tests pass -  an error appears at the end. 
Error: child_process.js:660

[michelles_workflow.pdf](https://github.com/DevExpress/testcafe-action/files/4202785/michelles_workflow.pdf)
[PASSES.pdf](https://github.com/DevExpress/testcafe-action/files/4202787/PASSES.pdf)
[FailChildProcess.pdf](https://github.com/DevExpress/testcafe-action/files/4202789/FailChildProcess.pdf)

When I run the same workflow again it runs and passes.
It happens randomly from time to time. Any ideas?

I have attached my is my actions workflow (michelles_workflow) and the good log (PASSES) and the error log (FailChildProcess)

Thanks for your consideration!
Regards
Michelle Macdonald

**Comment by AlexKamaev** [comment]
Hello @mishmaccas 
Please run the workflow on Windows. Does the issue persist?
