### ISSUE TITLE
How to start a server before running the action?

### ISSUE THREAD

**Issue by Asuza** [DevExpress/testcafe-action#19]
As far as I can tell, there is no way to customize the starting command for this GitHub action, and I need to start a small server before the tests run for them to work properly.

How I'm doing this locally is via the `start-server-and-test` npm module, using the following scripts in my _package.json_:
```
  "scripts": {
    "start-test-server": "vue-cli-service serve --mode production --port 8081",
    "start-ui-tests": "testcafe chrome tc/Tests/*",
    "ci": "start-server-and-test start-test-server 8081 start-ui-tests"
  },
```

However, I'm not sure how to translate this to be used with the TestCafe GitHub Action, because it always runs the `testcafe` command with no way to change it (again, that I know of). Is something like this possible, or do I need to go back to the drawing board?

Thank you.

**Comment by AlexKamaev** [comment]
You can use the `--app` and `--app-init-delay` properties to specify the shell command before tests start. Please refer to the following article for details: https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#-a-command---app-command

Thus, you can add these properties to the `args` argument in your workflow.yml file.
```
- name: Run TestCafe Tests
   uses: DevExpress/testcafe-action@latest
       with:
           args: chrome tests --app "http-server"
```
Please also note that there is an [issue](https://github.com/DevExpress/testcafe-action/issues/16) with the GitHub action and Windows environment. Take a look at that ticket to see examples and a workaround.
If you still have any questions, feel free to ask them here.
