### ISSUE TITLE
Urgent - testcafe report

### ISSUE THREAD

**Issue by Kaushalya88** [DevExpress/testcafe-action#30]
hello, i tried to output testcafe results to external file but no luck with me, in my testcafe project,
reporter: [
        {
            "name": "spec"
        },
        {
            "name": "xunit",
            "output": "reports/xunit/report.xml"
        }
    ]
when i run locally it outputs to report.xml, but with githubaction i just gave 
 - name: Run TestCafe tests on Chrome
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome tests/homepage/*.js --reporter xunit: reports/xunit/report.xml"

and even 
 - name: Run TestCafe tests on Chrome
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome tests/homepage/*.js " but seems the content of the xml file is empty, please assist me in this.

**Comment by AlexKamaev** [comment]
I think you need to upload the report file as an artifact.
Please refer to the following article for more details: [https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts).

I prepared a sample workflow that demonstrates how to store a testcafe report as an artifact:

```JS
name: End-to-End Tests
on: [push]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome tests --reporter xunit:reports/xunit/report.xml"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: reports/xunit/report.xml
          retention-days: 5

```
