### ISSUE TITLE
“latest” tag is out of date

### ISSUE THREAD

**Issue by rybesh** [DevExpress/testcafe-action#34]
The `latest` tag no longer points to the latest version of this action:

https://github.com/DevExpress/testcafe-action/tree/latest

As a result those who follow the instructions to put `uses: DevExpress/testcafe-action@latest` in their workflow config will get an out-of-date version of the action (and deprecation warnings).

**Comment by Aleksey28** [comment]
Hi @rybesh,

Thank you for noticing this. I've updated the latest tag.
